<?php
	
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'السماح للمستخدمين ذوي المشاركات بتغيير أسمائهم:',
		'allow_close_questions' => 'السماح بغلق الأسئلة يدوياً:',
		'allow_login_email_only' => 'الدخول فقط بعنوان البريد الإلكتروني (وليس باسم المستخدم):', 
		'allow_multi_answers' => 'السماح بالإجابات المتعددة للمستخدم الواحد:',
		'allow_no_category' => 'السماح بالأسئلة عير المصنفة',
		'allow_no_sub_category' => 'السماح بأسئلة ذات تصنيف ولكن ليس بتصنيف فرعي',
		'allow_private_messages' => 'السماح بالرسائل الخاصة بين المستخدمين:',
		'allow_self_answer' => 'السماح للمستخدمين بالرد على أسئلتهم الخاصة:',
		'allow_view_q_bots' => 'السماح لمحركات البحث بعرض صفحات السؤال',

		'allow_user_walls' => "تمكين مشاركات الملصق على ملفات المستخدمين:",
		'approve_user_required' => "يجب اعتماد جميع المستخدمين الجدد:",
		'avatar_message_list_size' => "حجم الصورة المستعارة على قائمة الرسائل:",		
		'avatar_allow_gravatar' => 'السماح ^1 بالصور الشخصية (Gravatar^2):',
		'avatar_allow_upload' => 'السماح للمستخدمين برفع الصور الشخصية:',
		'avatar_default_show' => 'الصورة الشخصية الافتراضية:',
		'avatar_profile_size' => 'حجم الصورة الشخصية في الملف الشخصي للمستخدم (بالبكسل):',
		'avatar_q_list_size' => 'حجم الصور الشخصية في قوائم الأسئلة (بالبكسل):',
		'avatar_q_page_a_size' => 'حجم الصور الشخصية في الإجابات (بالبكسل):',
		'avatar_q_page_c_size' => 'حجم الصور الشخصية في التعليقات (بالبكسل):',
		'avatar_q_page_q_size' => 'حجم الصور الشخصية في الأسئلة (بالبكسل):',
		'avatar_store_size' => 'الحجم الأقصى للصور الشخصية المخزنة (بالبكسل):',
		'avatar_users_size' => 'حجم الصور الشخصية في أعلى صفحات المستخدمين (بالبكسل):',
		'block_bad_words' => 'الكلمات المحظورة (افصل بين كل كلمة وأخرى بمسافة أو فاصلة):',
		'block_ips_write' => 'عناوين IP المحظورة (افصل بين كل عنوان وآخر بمسافة أو فاصلة):',
		'captcha_module' => 'استخدم نموذج الصورة التأكيدية (reCAPTCHA):',
		'captcha_on_anon_post' => 'استخدم الصورة التأكيدية (reCAPTCHA) للمستخدمين المجهولين:',
		'captcha_on_feedback' => 'استخدم الصورة التأكيدية (reCAPTCHA) في نموذج اتصل بنا:',
		'captcha_on_register' => 'استخدم الصورة التأكيدية (reCAPTCHA) عند تسجيل المستخدمين:',
		'captcha_on_reset_password' => 'استخدم الصورة التأكيدية (reCAPTCHA) في نموذج استعادة كلمة المرور:',
		'captcha_on_unconfirmed' => 'استخدم الصورة التأكيدية (reCAPTCHA) في الإدراجات إذا لم يتم تأكيد البريد الإلكتروني:',
		'columns_tags' => 'أعمدة صفحة الوسوم:',		'captcha_on_unapproved' => "استخدم مانع الازعاج إذا لم يعتمد بعد:",
		'columns_users' => 'أعمدة صفحة المستخدمين:',
		'comment_on_as' => 'السماح بالتعليقات على الإجابات:',
		'comment_on_qs' => 'السماح بالتعليقات على الأسئلة:',
		'confirm_user_emails' => 'طلب تأكيد البريد الإلكتروني للمستخدم:',
		'confirm_user_required' => 'المستخدمون الجدد ملزمون باستكمال عملية التأكيد:',
		'custom_home_content' => 'المحتويات التي ستعرض في الصفحة الرئيسية (مسموح بأكواد HTML):',
		'custom_home_heading' => 'العنوان المعروض في أعلى الصفحة الرئيسية:',
#		'custom_welcome' => ' رسالة مخصصة لتدرج في البريد الإلكتروني للمستخدمين الجدد:',
		'default_privacy' => 'لا تقلق بشأن الخصوصية: لن نشارك أو نبيع عنوان بريدك الإلكتروني لطرف ثالث.',
		'default_sidebar' => "مرحبًا بك إلى ^، حيث يمكنك طرح الأسئلة وانتظار الإجابة عليها من المستخدمين الآخرين.",
		'default_subject' => 'رسالة من ^',
		'default_suffix' => 'س&ج',
		'default_terms' => 'أنا موافق على ^ الشروط والأحكام وسياسة الخصوصية',
		'do_ask_check_qs' => 'تفحص وجود أسئلة مشابهة عند طرح سؤال:',
		'do_close_on_select' => 'اغلق السؤال بإجابة مختارة:',
		'do_complete_tags' => 'عرض الوسوم المتطابقة عند كتابة الوسوم:',
		'do_count_q_views' => 'إحصاء عدد مرات عرض السؤال:',
		'do_example_tags' => 'عرض أمثلة للوسوم معتمدة على السؤال:',
#		'do_related_qs' => 'عرض الأسئلة المتعلقة في صفحة السؤال:',
		'editor_for_as' => 'المحرر الافتراضي للإجابات:',
		'editor_for_cs' => 'المحرر الافتراضي للتعليقات:',
		'editor_for_qs' => 'المحرر الافتراضي للأسئلة:',
		'email_privacy' => 'ملاحظة الخصوصية للبريد الإلكتروني في جميع النماذج (مسموح بأكواد HTML):',
		'extra_field_active' => 'حقل مخصص لبيانات إضافية في نموذج السؤال:',
		'extra_field_display_label' => 'اظهر البيانات الإضافية على صفحات السؤال بعنوان:',
		'extra_field_display' => 'اظهر البيانات الإضافية على صفحات السؤال',
		'feed_for_activity' => 'التغذية للأسئلة والإجابات والتعليقات الجديدة:',
		'feed_for_hot' => 'التغذية للأسئلة الساخنة:',
		'feed_for_qa' => 'التغذية للأسئلة والإجابات الجديدة:',
		'feed_for_questions' => 'التغذية للأسئلة الجديدة:',
		'feed_for_search' => 'التغذية لنتائج البحث:',
		'feed_for_tag_qs' => 'التغذية للأسئلة الجديدة لكل وسم:',
		'feed_for_unanswered' => 'التغذية للأسئلة الجديدة غير المجابة:',
		'feed_full_text' => 'إدراج النص بالكامل في التغذية:',
		'feed_number_items' => 'أقصى عدد للعناصر في التغذية:',
		'feed_per_category' => 'أيضًا قدم تغذية منفصلة لكل تصنيف:',
		'feedback_email' => 'عناوين البريد الإلكتروني لرسائل المدير (غير مرئية للمستخدمين):',
		'feedback_enabled' => 'توفير نموذج للسماح للمستخدمين بالاتصال (صفحة اتصل بنا)',
		'flagging_hide_after' => 'إخفاء تلقائي للمشاركات التي تصل:',
		'flagging_notify_every' => 'مراسلتي مرة ثانية بعد كل:',
		'flagging_notify_first' => 'راسلني إذا استلمت المشاركة:',
		'flagging_of_posts' => 'السماح بتعليم المشاركات:',
		'follow_on_as' => 'السماح بالأسئلة الجديدة المتعلقة بالإجابات:',
		'from_email' => 'عنوان الراسل لجميع رسائل الإدارة الإلكترونية:',
		'hot_weight_a_age' => 'السؤال يحوي إجابة:',
		'hot_weight_answers' => 'السؤال يحوي العديد من الإجابات:',
		'hot_weight_q_age' => 'السؤال جديد:',
		'hot_weight_views' => 'السؤال يتمتع بزيارات عديدة:',
		'hot_weight_votes' => 'السؤال يتمتع بتقييمات إيجابية عديدة:',
		'links_in_new_window' => 'افتح روابط URLs في نافذة جديدة:',
		'logo_height' => 'ارتفاع الشعار بالبكسل:',
		'logo_show' => 'عرض شعار للموقع في أعلى الصفحة',
		'logo_url' => 'عنوان URL للشعار (عنوان http:// كامل، أو بالنسبة للمجلد الرئيسي الموجود به ملفات سكربت س☼ج):',
		'logo_width' => 'عرض الشعار بالبكسل:',
		'mailing_body' => 'نص الموضوع:',
		'mailing_enabled' => 'تمكين المراسلة الكمية لجميع المستخدمين',
		'mailing_from_email' => 'من العنوان البريدي:',
		'mailing_from_name' => 'من الاسم:',
		'mailing_per_minute' => 'معدل المراسلة الأعظمي:',
		'mailing_subject' => 'سطر الموضوع:',
		'match_1' => 'الأكثر مطابقة',
		'match_2' => 'أكثر مطابقة',
		'match_3' => 'الإعدادات الافتراضية (مستحسن)',
		'match_4' => 'أقل مطابقة',
		'match_5' => 'الأقل مطابقة',
		'match_ask_check_qs' => 'الأسئلة المتشابهة المتطابقة:',
		'match_example_tags' => 'أمثلة الوسوم المتطابقة:',
		'match_related_qs' => 'الأسئلة المتعلقة المتطابقة:',
		'max_len_q_title' => 'أقصى عدد للحروف في عنوان السؤال:',
		'max_num_q_tags' => 'أقص عدد من الوسوم للسؤال:',
		'max_rate_ip_as' => 'أقصى عدد من الإجابات لكل عنوان IP في الساعة:',
		'max_rate_ip_cs' => 'أقصى عدد للتعليقات لكل عنوان IP في الساعة:',
		'max_rate_ip_flags' => 'أقصى عدد تعليم المشاركات:',
		'max_rate_ip_logins' => 'أقصى عدد من محاولات تسجيل الدخول لكل عنوان IP في الساعة:',
		'max_rate_ip_messages' => 'أقصى عدد طرح الرسائل الخاصة:',
		'max_rate_ip_qs' => 'أقصى عدد للأسئلة لكل عنوان IP في الساعة:',
		'max_rate_ip_registers' => 'أقصى عدد اشتراكات المستخدم:',
		'max_rate_ip_uploads' => 'أقصى عدد رفع الملفات:',
		'max_rate_ip_votes' => 'أقصى عدد من التصويتات لكل عنوان IP في الساعة:',
		'max_rate_user_as' => 'أقصى عدد من الإجابات لكل عضو في الساعة:',
		'max_rate_user_cs' => 'أقصى عدد من التعليقات لكل عضو في الساعة:',
		'max_rate_user_flags' => 'أقصى عدد تعليمات لكل مستخدم في الساعة:',
		'max_rate_user_messages' => 'أقصى عدد رسائل خاصة لكل مستخدم في الساعة:',
		'max_rate_user_qs' => 'أقصى عدد من الأسئلة لكل عضو في الساعة:',
		'max_rate_user_uploads' => 'أقصى عدد عمليات رفع للمستخدم في الساعة:',
		'max_rate_user_votes' => 'أقصى عدد من التصويتات لكل عضو في الساعة:',
		'min_len_a_content' => 'أقصى عدد من الحروف للإجابة:',
		'min_len_c_content' => 'أقص عدد من الحروف للتعليق::',
		'min_len_q_content' => 'أقل عدد من الحروف لجسم السؤال:',
		'min_len_q_title' => 'أقل عدد من الحروف لعنوان السؤال:',
		'min_num_q_tags' => 'أقل عدد من وسوم السؤال:',
		'moderate_anon_post' => 'استخدم الاعتدال للمشاركات المجهولة:',
		'moderate_by_points' => 'استعمل الاعتدال للمستخدمين ذوي النقاط القليلة:',
		'moderate_notify_admin' => 'راسلني حين تحتاج مشاركة إلى اعتدال:',
		'moderate_points_limit' => 'استعمل الاعتدال للمستخدمين بأقل من:',
		'moderate_unconfirmed' => 'استعمل الاعتدال إذا لم يتم تأكيد البريد:',
		'moderate_edited_again' => "إعادة إدارة المشاركات بعد التعديل:",
		'moderate_unapproved' => "استعمل الإدارة إذا لم يكن المستخدم قد تم اعتماده:",
		'moderate_update_time' => "مدة إظهار المشاركات المدارة:",
		'moderate_users' => "تمكين إدارة (الموافقة) المستخدمين:",
		'neat_urls' => 'تركيبة عنوان URL للصفحة في الموقع:',
		'notify_admin_q_post' => 'أعلمني على هذا العنوان البريدي إذا ما تم طرح أسئلة جديدة',
		'notify_users_default' => 'تفعيل علامة إعلام البريد بشكل افتراضي:',
		'option_default' => 'افتراضي',
		'page_size_activity' => 'طول كل نشاط الصفحة:',
		'page_size_ask_check_qs' => 'أقصى عدد من الأسئلة المتشابهة للعرض:',
		'page_size_ask_tags' => 'أقصى عدد من تلميحات الوسم للعرض:',
		'page_size_home' => 'طول الصفحة الرئيسية:',
		'page_size_hot_qs' => 'طول الصفحة الساخنة:',
		'page_size_pms' => 'رسائل خاصة لكل صفحة:',
		'page_size_q_as' => 'أقصى عدد إجابات في الصفحة:',
		'page_size_qs' => 'طول صفحة الأسئلة:',
		'page_size_related_qs' => 'أقصى عدد من الأسئلة المتعلقة:',
		'page_size_search' => 'الأسئلة في صفحة البحث:',
		'page_size_tag_qs' => 'الأسئلة في صفحة الوسوم:',
		'page_size_tags' => 'طول صفحة الوسوم:',
		'page_size_una_qs' => 'طول صفحة الأسئلة غير المجابة:',
#		'page_size_user_posts' => 'الإدراجات في صفحة المستخدم:',
		'page_size_users' => 'طول صفحات المستخدمين:',
		'pages_prev_next' => 'الوصلات للصفحات التالية/السابقة:',
		'page_size_wall' => "عدد المشاركات في الصفحة:",
		'permit_admins' => 'المدراء',
		'permit_all' => 'أي شخص',
#		'permit_anon_view_ips' => 'عرض عناوين IP للمستخدمين المجهولين:',
		'permit_block' => 'حظر أو رفع الحظر عن مستخدم أو عناوين IP:',
		'permit_confirmed' => 'المستخدمون المسجلون مع بريد مفعل',
		'permit_create_admins' => 'إنشاء مدراء:',
		'permit_create_eds_mods' => 'إنشاء محررين ووسطاء:',
		'permit_create_experts' => 'إنشاء خبراء:',
		'permit_delete_users' => 'حذف المستخدمين:',
#		'permit_delete_hidden' => 'حذف الإدراجات المخفية:',
#		'permit_edit_a' => 'تعديل أي إجابة:',
#		'permit_edit_c' => 'تعديل أي تعليق:',
#		'permit_edit_q' => 'تعديل أي سؤال:',
		'permit_editors' => 'المحررون، والوسطاء، والمدراء',
		'permit_experts' => 'الخبراء، والمحررون، والوسطاء، والمدراء',
#		'permit_hide_show' => 'إخفاء أي إدراج:',
		'permit_moderators' => 'الوسطاء والمدراء',
		'permit_points_confirmed' => 'المسجلين، البريد المؤكد، النقاط الكافية',
		'permit_points' => 'المستخدمين المسجلين مع نقاط كافية',
#		'permit_post_a' => 'إضافة الإجابات:',
#		'permit_post_c' => 'إضافة التعليقات:',
#		'permit_post_q' => 'إضافة الأسئلة:',
		'permit_see_emails' => 'مشاهدة عناوين المستخدمين الإلكترونية:',
#		'permit_select_a' => 'اختيار إجابة لكل الأسئلة:',
		'permit_supers' => 'المدراء الفوقيون',
		'permit_users' => 'المستخدمون المسجلون',
#		'permit_vote_a' => 'التصويت للإجابات:',
#		'permit_vote_q' => 'التصويت للأسئلة:',
		'permit_approve_users' => "اعتماد المستخدمين المسجلين:",
		'permit_approved' => "تم اعتماد المستخدمين فقط",
		'permit_approved_points' => "تم اعتماد المستخدمين بالنقاط الكافية",
		'place_full_below_content' => 'عرض كامل - تحت المحتوى',
		'place_full_below_footer' => 'عرض كامل - تحت التذييل',
		'place_full_below_nav' => 'عرض كامل - تحت الاستكشاف',
		'place_full_top' => 'عرض كامل - فوق الصفحة',
		'place_main_below_lists' => 'منطقة رئيسة - تحت القوائم',
		'place_main_below_title' => 'منطقة رئيسية تحت العنوان',
		'place_main_bottom' => 'منطقة رئيسة - أسفل',
		'place_main_top' => 'منطقة رئيسة - أعلى',
		'place_side_below_categories' => 'لوحة جانبية - أسفل التصنيفات',
		'place_side_below_sidebar' => 'لوحة جانبية - أسفل صندوق الشريط الجانبي',
		'place_side_last' => 'لوحة جانبية - الأخير',
		'place_side_top' => 'لوحة جانبية  - الأعلى',
		'points_a_selected' => 'اختيار إجابتك كالإجابة المثلى:',
		'points_a_voted_max_gain' => 'الحد من التصويتات الموجبة لكل إجابة:',
		'points_a_voted_max_loss' => 'الحد من التصويتات السالبة لكل إجابة:',
		'points_base' => 'إضافة لجميع المستخدمين:',
		'points_multiple' => 'ضرب جميع النقاط:',
#		'points_per_a_voted' => 'لكل تصويت موجب/سالب في إجابتك:',
#		'points_per_q_voted' => 'لكل تصويت موجب/سالب في سؤالك:',
		'points_per_a_voted_down' => 'لكل تصويت سلبي عن إجابتك:',
		'points_per_a_voted_up' => 'لكل تصويت إيجابي عن إجابتك:',
		'points_per_q_voted_down' => 'لكل تصويت سلبي عن سؤالك:',
		'points_per_q_voted_up' => 'لكل تصويت إيجابي عن سؤالك:',
		'points_post_a' => 'إرسال إجابة:',
		'points_post_q' => 'إرسال سؤال:',
		'points_q_voted_max_gain' => 'الحد من التصويتات الموجبة لكل سؤال:',
		'points_q_voted_max_loss' => 'الحد من التصويتات السالبة لكل سؤال:',
		'points_select_a' => 'اختيار أفضل إجابة لسؤالك:',
		'points_vote_down_a' => 'التصويت بالسلب لإجابة:',
		'points_vote_down_q' => 'التصويت بالسلب لسؤال:',
		'points_vote_up_a' => 'التصويت بالإيجاب لإجابة:',
		'points_vote_up_q' => 'التصويت بالإيجاب لسؤال:',
#		'recaptcha_private_key' => 'مفتاح صورة التأكيد (reCAPTCHA) الخاصة بك:',
#		'recaptcha_public_key' => 'مفتاح صورة التأكيد (reCAPTCHA) العام:',
		'q_urls_remove_accents' => 'إزالة التشكيلات من روابط URLs:',
		'q_urls_title_length' => 'طول عنوان السؤال في روابط URLs:',
		'register_notify_admin' => "راسلني كلما سجل مستخدم جديد:",
		'search_module' => 'استخدام نموذج البحث:',
		'show_a_form_immediate' => 'عرض نموذج الإجابة في الحال:',
		'show_always' => 'دائمًا',
		'show_c_reply_buttons' => 'عرض أزرار الرد للتعليقات:',
		'show_custom_answer' => 'خاص لنموذج الإجابة - كود HTML مسموح:',
		'show_custom_ask' => 'خاص لنموذج السؤال - كود HTML مسموح:',
		'show_custom_comment' => 'خاص لنموذج  التعليق- كود HTML مسموح:',
		'show_custom_footer' => 'كود HTML خاص لأسفل كل صفحة:',
		'show_custom_header' => 'كود HTML خاص لأعلى كل صفحة:',
		'show_custom_home' => 'محتوى خاص للصفحة الرئيسية (عوضًا عن س☼ج)',
		'show_custom_in_head' => 'كود HTML خاص في وسم <HEAD> لكل صفحة:',
		'show_custom_register' => 'كود HTML خاص للتسجيل:',
		'show_custom_sidebar' => 'كود HTML خاص لصندوق الشريط الجانبي في كل صفحة:',
		'show_custom_sidepanel' => 'كود HTML خاص للوحة الجانبية في كل صفحة:',
		'show_custom_welcome' => 'كود HTML خاص  بالبريد المرسل للمسجلين الجدد:',
		'show_post_update_meta' => 'عرض التعديلات / التحديثات في عرض الميتا:',
		'show_fewer_cs_count' => 'إذا كانت مخفية جزئياً، اظهر الأحدث:',
		'show_fewer_cs_from' => 'اخف التعليقات جزئيا إذات تجاوزت:',
		'show_full_date_days' => 'اظهر التاريخ كاملاً بعد:',
		'show_home_description' => 'إضاقة وصف <META> للصفحة الرئيسبة:',
		'show_if_no_as' => 'في حالة عدم وحود إجابات',
		'show_message_history' => 'تخزين وعرض سجل تاريخ الرسائل الخاصة:',
		'show_never' => 'أبداً',
		'show_notice_visitor' => 'كود HTML - ملاحظة في الأعلى للزوار الجدد:',
		'show_notice_welcome' => 'كود HTML - ملاحظة في الأعلى للمسجلين الجدد:',
		'show_register_terms' => "مسموح HTML - شروط و أحكام خانة الاختيار على استمارة التسجيل:",
		'show_selected_first' => 'تحريك الإجابات المختارة إلى الإعلى:',
		'show_url_links' => 'كشف وربط عناوين URL في النص المدخل:',
		'show_user_points' => 'عرض النقاط بجوار اسم المستخدم:',
		'show_user_titles' => 'عرض الرتبة بجوار اسم المستخدم:',
		'show_view_counts' => 'اظهار عدد المشاهدات في قوائم السؤال:',
		'show_when_created' => 'عرض عمر محتوى المستخدم:',
		'site_language' => 'لغة واجهة الموقع:',
		'site_maintenance' => 'إغلاق الموقع للصيانة',
		'site_text_direction' => "اتجاه نص الموقع:",
		'site_theme_mobile' => 'السمة للموبايل:',
		'site_theme' => 'سمة الموقع:',
		'site_title' => 'اسم الموقع (للعرض في عناوين الصفحات):',
		'site_url' => 'عنوان URL المستخدم للإشارة للموقع:',
		'smtp_active' => 'ارسال بريد عبر SMTP بدلاً عن البريد المحلي',
		'smtp_address' => 'عنوان خادم SMTP:',
		'smtp_authenticate' => 'ارسال اسم مستخدم SMTP وكلمة المرور',
		'smtp_password' => 'كلمة مرور SMTP:',
		'smtp_port' => 'منفذ خادم SMTP:',
		'smtp_secure_none' => 'لا يوجد',
		'smtp_secure' => 'اتصال SMTP الآمن:',
		'smtp_username' => 'اسم مستخدم SMTP:',
		'sort_answers_by' => 'ترتيب الإجابات بحسب:',
		'sort_time' => 'الوقت',
		'sort_votes' => 'التصويتات',
		'suspend_register_users' => 'تم تعطيل الاشتراكات الجديدة مؤقتاً:',
		'show_view_count_q_page' => "اظهار عدد المشاهدات على صفحات الأسئلة:",
		'time_approved' => "وقت الاعتماد",
		'time_written' => "وقت الكتابة",
		'tag_separator_comma' => 'استخدم الفاصلة فقط:',
		'tags_or_categories' => 'تصنيف الأسئلة بحسب:',
		'votes_separated' => 'عرض التصويتات الموجبة والسالبة منفصلة:',
		'voting_on_as' => 'السماح بالتصويت للإجابات:',
		'voting_on_q_page_only' => 'السماح بالتصويت في صفحة السؤال فقط:',
		'voting_on_qs' => 'السماح بالتصويت للأسئلة:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
