<?php
	
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-users.php
	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 إجابة',
		'1_comment' => '1 تعليق',
		'1_day' => '1 يوم',
		'1_disliked' => '1 شخص غير معجب',
		'1_flag' => '1 إبلاغ إساءة',
		'1_hour' => '1 ساعة',
		'1_liked' => '1 شخص معجب',
		'1_minute' => '1 دقيقة',
		'1_month' => '1 شهر',
		'1_point' => '1 نقطة',
		'1_question' => '1 سؤال',
		'1_second' => '1 ثانية',
		'1_tag' => '1 وسم',
		'1_user' => '1 عضو',
		'1_view' => '1 عرض',
		'1_vote' => '1 تصويت',
		'1_week' => '1 أسبوع',
		'1_year' => '1 سنة',
		'add_category_x_favorites' => 'إضافة التصنيف ^ إلى المفضلة',
		'add_favorites' => 'إضافة إلى المفضلة',
		'add_tag_x_favorites' => 'إضافة وسم ^ إلى المفضلة',
		'all_categories' => 'جميع التصنيفات',
		'anonymous' => 'مجهول',
		'answer_edited' => 'تم تعديل الإجابة',
		'answer_reshown' => 'تم عرض الإجابة مرة أخرى',
		'answer_selected' => 'تم اختيار الإجابة',
		'answered_qs_in_x' => 'أكثر الأسئلة المجاب عنها في ^',
		'answered_qs_title' => 'أكثر الأسئلة المجاب عنها',
		'answered' => 'تم الرد عليه',
		'asked_related_q' => 'سؤال ذا صلة',
		'asked' => 'سُئل',
		'by_x' => 'بواسطة ^',
		'cancel_button' => 'إلغاء',
		'closed' => 'مغلق',		
		'comment_edited' => 'تم تعديل التعليق',
		'comment_moved' => 'تم نقل التعليق',
		'comment_reshown' => 'تم إظهار التعليق مرة أخرى',
		'commented' => 'تم التعليق عليه',

		'date_day_min_digits' => "1",
		'date_format_other_years' => "^month ^day، ^year",
		'date_format_this_year' => "^month ^day",
		'date_month_1' => "يناير",
		'date_month_2' => "فبراير",
		'date_month_3' => "مارس",
		'date_month_4' => "أبريل",
		'date_month_5' => "مايو",
		'date_month_6' => "يونيو",
		'date_month_7' => "يوليو",
		'date_month_8' => "أغسطس",
		'date_month_9' => "سبتمبر",
		'date_month_10' => "أكتوبر",
		'date_month_11' => "نوفمبر",
		'date_month_12' => "ديسمبر",
		'date_year_digits' => "4",

		'edited' => 'عُدل',
		'email_error' => 'حدث خطأ أثناء محاولة إرسال البريد الإلكتروني.',
		'field_required' => 'من فضلك، اكتب شيئًا في هذا الحقل',
		'file_upload_limit_exceeded' => 'حجم الملف يتجاوز حدود المسموح به في الخادم',
		'general_error' => 'حدث خطأ في الخادم، برجاء المحاولة مرة أخرى.',
		'hidden' => 'مخفي',
		'highest_users' => 'أعلى الأعضاء نقاطًا',
		'hot_qs_in_x' => 'أسئلة ساخنة في تصنيف: ^',
		'hot_qs_title' => 'أسئلة ساخنة',
		'image_not_read' => 'تعذرت قراءة الصورة. الرجاء تحميل واحدة: ^',
		'image_too_big_x_pc' => 'هذه الصورة كبيرة جداً. الرجاء إعادة تحجيمها إلى ^% والمحاولة مرة أخرى.',
		'in_category_x' => 'في تصنيف ^',
		'ip_address_x' => 'عنوان IP ^',
		'logged_in_x' => 'مرحبًا ^',
		'max_length_x' => 'أقصى طول هو ^ حرفًا',
		'max_upload_size_x' => "السعة الأعظمية للرفع هي ^",
		'me' => 'أنا',
		'meta_order' => "^what^when^where^who",
		'min_length_x' => 'من فضلك قدم المزيد من المعلومات [على الأقل ^ حرفًا]',
		'moved' => 'تم النقل',
		'nav_activity' => 'كل الأنشطة',
		'nav_admin' => 'لوحة التحكم',
		'nav_ask' => 'اطرح سؤالاً',
		'nav_categories' => 'التصنيفات',
		'nav_feedback' => 'اتصل بنا',
		'nav_home' => 'الرئيسية',
		'nav_hot' => 'نقاشات ساخنة!',
		'nav_login' => 'تسجيل الدخول',
		'nav_logout' => 'تسجيل الخروج',
		'nav_most_answers' => 'أكثر الإجابات',
		'nav_most_recent' => 'الأحدث',
		'nav_most_views' => 'الأكثر عرضاً',
		'nav_most_votes' => 'أكثر التقييمات',
		'nav_no_answer' => 'لا إجابة',
		'nav_no_selected_answer' => 'إجابة غير مختارة',
		'nav_no_upvoted_answer' => 'إجابة لم يتم تقييمها',
		'nav_qa' => 'سؤال وإجابة',
		'nav_qs' => 'الأسئلة',
		'nav_register' => 'تسجيل',
		'nav_tags' => 'الوسوم',
		'nav_unanswered' => 'الأسئلة غير المجابة',
		'nav_updates' => 'تحديثاتي',
		'nav_users' => 'الأعضاء',
		'no_active_users' => 'لم يتم إيجاد مستخدمين نشطين',
		'no_answers_found' => 'لم يتم العثور على إجابات',
		'no_answers_in_x' => 'لا إجابات لـ ^',
		'no_categories_found' => 'لم يتم إيجاد أي تصنيفات',
		'no_category' => 'لا تصنيف',
		'no_comments_found' => 'لا توجد تعليقات',
		'no_comments_in_x' => 'لا توجد تعليقات في ^',
#		'no_questions_found_in_x' => 'لا توجد أسئلة في ^',
		'no_questions_in_x' => 'لا توجد أسئلة في ^',
		'no_questions_found' => 'لم يتم إيجاد أسئلة',
		'no_related_qs_title' => 'لم يتم إيجاد أسئلة ذات علاقة',
		'no_results_for_x' => 'لا توجد نتائج لـ ^',
		'no_tags_found' => 'لم يتم إيجاد وسوم',
		'no_una_questions_found' => 'لا توجد أسئلة غير مجابة',
		'no_una_questions_in_x' => 'لا توجد أسئلة غير مجابة في ^',
		'no_unselected_qs_found' => 'لا توجد أسئلة بدون إجابة مختارة',
		'no_unupvoteda_qs_found' => 'لا توجد أسئلة بدون إجابة مقيمة',
		'page_label' => 'صفحة:',
		'page_next' => 'التالي',
		'page_not_found' => 'لم يتم إيجاد الصفحة',
		'page_prev' => 'السابق',
		'popular_tags' => 'الوسوم الأكثر شعبية',
		'questions_tagged_x' => 'آخر الأسئلة في وسم ^',
		'recategorized' => 'أعيد الوسم',
		'recent_activity_in_x' => 'آخر الأنشطة في ^',
		'recent_activity_title' => 'آخر الأنشطة',
		'recent_as_in_x' => 'آخر الأسئلة المجابة  في ^',
		'recent_as_title' => 'آخر الأسئلة المجابة',
		'recent_cs_in_x' => 'آخر التعليقات المضافة في ^',
		'recent_cs_title' => 'آخر التعليقات المضافة',
		'recent_qs_as_in_x' => 'آخر الأسئلة والإجابات في ^',
		'recent_qs_as_title' => 'آخر الأسئلة والإجابات',
		'recent_qs_in_x' => 'آخر الأسئلة في ^',
		'recent_qs_title' => 'آخر الأسئلة',
		'related_qs_title' => 'اسئلة متعلقة',
		'remove_favorites' => 'ازل من المضلة',
		'remove_x_favorites' => 'ازل ^ من المضلة',
		'reopened' => 'تم الفتح مرة أخرى',
		'reshown' => 'تم الإظهار مرة أخرى',
		'results_for_x' => 'ابحث عن النتائج لـ ^',
		'retagged' => 'أعيد الوسم',
		'save_button' => 'احفظ التغييرات',
		'search_button' => 'بحث',
		'search_explanation' => 'يرجى إدخال بعض العبارات إلى مربع البحث والمحاولة مرة أخرى.',
		'search_title' => 'ابحث عن أسئلة',
		'selected' => 'مختارة',
		'send_button' => 'ارسل',
		'since_x' => 'منذ ^',
		'suggest_ask' => 'هل تحتاج لمساعدة؟ ^1اطرح سؤالك الآن!^2.',
		'suggest_category_qs' => 'Tلمشاهدة المزيد، انقر للحصول على جميع ^1الأسئلة في هذا التصنيف^2.',
		'suggest_qs_tags' => 'لمشاهدة المزيد، انقر على ^1القائمة الكاملة للأسئلة^2 أو ^3 الوسوم الشائعة^4.',
		'to_x' => 'إلى ^',
		'suggest_qs' => 'لمشاهدة المزيد، انقر على ^1القائمة الكاملة للأسئلة^2.',
		'unanswered_qs_in_x' => 'أحدث الأسئلة غير المجاب عنها في ^',
		'unanswered_qs_title' => 'أحدث الأسئلة غير المجاب عنها',
		'unselected_qs_in_x' => 'أسئلة لم يتم اختيار إجابتها في ^',
		'unselected_qs_title' => 'أسئلة جارية لم يتم إختيار إجابة لها',
		'unupvoteda_qs_in_x' => 'أسئلة جارية بإجابات لم يتم تقييمها في ^',
		'unupvoteda_qs_title' => 'أسئلة جارية بإجابات لم يتم تقييمها',
		'upload_limit' => 'هناك العديد من عمليات الرفع حالياً - الرجاء المحاولة بعد ساعة',
		'view_q_must_confirm' => 'من فضلك  ^5قم بتأكيد عنوان بريدك^6 لعرض صفحات السؤال.',
		'view_q_must_login' => 'من فضلك ^1قم بتسجيل الدخول ^2 أو ^3أو اشترك الآن^4 لعرض صفحات السؤال.',
		'viewed_qs_in_x' => 'أكثر الأسئلة المعروضة في ^',
		'viewed_qs_title' => 'أكثر الأسئلة المعروضة',
		'vote_disabled_down' => 'التقييم السيء متاح فقط لبعض المستخدمين',
		'vote_disabled_hidden_a' => 'لا يمكنك التصويت لإجابات مخفية',
		'vote_disabled_hidden_q' => 'لا يمكنك التصويت لأسئلة مخفية',
		'vote_disabled_q_page_only' => 'من فضل شاهد السؤال أولاً لتتمكن من التصويت',
		'vote_disabled_my_a' => 'لا يمكنك التصويت لإجاباتك',
		'vote_disabled_my_q' => 'لا يمكنك التصويت لأسئلتك',
		'vote_disabled_q_page_only' => 'يرجى عرض هذا السؤال لتقييمه',
		'vote_down_must_confirm' => 'فضلاً، ^5أكد بريدك الإلكتروني ^6 لكي تقيم سلباً	.',
		'vote_down_popup' => 'انقر لتصوت بالسلب',
		'vote_limit' => 'تم استلام الكثر من التصويتات، من فضل حاول مرة أخرة بعد فترة',
		'vote_must_confirm' => 'من فضلك ^5قم بتأكيد بريدك الإلكتروني^6 لتتمكن من التصويت.',
		'vote_must_login' => 'من فضلك ^1سجل دخولك^2 أو ^3قم بالتسجيل^4 لتتمكن من التصويت.',
		'vote_not_allowed' => 'غير مسموح بالتصويت',
		'vote_up_popup' => 'انقر للتصويت بالإيجاب',
		'voted_down_popup' => 'لقد قمت بالتصويب بالسلب، انقر لإزالة تصويتك',
		'voted_qs_in_x' => 'الأسئلة الأعلى تقييماً في ^',
		'voted_qs_title' => 'الأسئلة الأعلى تقييماً',
		'voted_up_popup' => 'لقد قمت بالتصويت، انقر لإزالة تصويتك',
		'view_q_must_be_approved' => "يجب الموافقة على حسابك كي تتمكن من عرض صفحات الأسئلة.",
		'vote_disabled_approve' => "يجب الموافقة على حسابك كي تتمكن من التصويت",
		'vote_disabled_down_approve' => "يجب الموافقة على حسابك كي تتمكن من التصويت السلبي",
		'vote_disabled_level' => "يقتصر التصويت على بعض المستخدمين فقط",
		'written' => "placeholder",
		'x_ago' => 'منذ ^',
		'x_answers' => '^ إجابة',
		'x_comments' => '^ تعليقات',
		'x_days' => '^ أيام',
		'x_disliked' => '^ شخص غير معجب',
		'x_flags' => '^ أعلام',
		'x_hours' => '^ ساعات',
		'x_liked' => '^ معجب',
		'x_minutes' => '^ دقائق',
		'x_months' => '^ شهور',
		'x_points' => '^ نقاط',
		'x_questions' => '^ أسئلة',
		'x_seconds' => '^ ثوان',
		'x_tags' => '^ وسم',
		'x_users' => '^ مستخدم',
		'x_views' => '^ مشاهدات',
		'x_votes' => '^ تصويتات',
		'x_weeks' => '^ أسابيع',
		'x_years' => '^ سنوات',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
