<?php
	
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-users.php
	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'الأدوات الإضافية المفعلة حالياً:',
		'add_category_button' => 'اضف تصنيف',
		'add_field_button' => 'اضف حقل',
		'add_link_button' => 'اضف رابط',
		'add_link_link' => ' - ^1اضف رابط^2',
		'add_new_field' => 'اضف حقل جديد',
		'add_new_title' => 'اضف عنوان جديد',
		'add_page_button' => 'اضف صفحة',
		'add_title_button' => 'اضف رتبة',
		'add_new_field' => 'اضف حقل جديد',
		'add_new_title' => 'اضف رتبة جديدة',
		'add_page_button' => 'اضف صفحة',
		'add_title_button' => 'اضف عنوان',
		'add_widget_button' => 'اضف أداة إضافية Widget',
		'add_widget_link' => ' - ^1اضف أداة widget^2',
		'admin_title' => 'لوحة التحكم',
		'approve_user_popup' => 'وافق على المستخدم',
		'after_footer' => 'بعد الروابط في التذييل',
		'after_main_menu' => 'بعد الأشرطة في الأعلى',
		'after_x_tab' => 'بعد "^" شريط',
		'after_x' => 'بعد "^"',
		'basic_editor' => 'محرر بسيط',
		'before_main_menu' => 'قبل الأشرطة في الأعلى',
		'block_ips_note' => 'استخدم الواصلة للنطاقات أو * لمطابقة أي عدد. أمثلة: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_user_popup' => 'حظر مستخدم',
		'block_words_note' => 'استخدم * لمطابقة أي أحرف. على سبيل المثال: ثدي (سوف تطابق كلمة "ثدي" فقط) ، ثدي* (سوف تطابق كلمة "ثدي" أو "ثدي11") ، ثد*ي (سوف تطابق كلمة "ثدي" و"ثد22ي" و"ثد11ي").',
		'blobs_directory_error' => "المجلد ^ المعروف باسم QA_BLOBS_DIRECTORY غير قابل للكتابة بواسطة خادم الويب.",
		'blobs_move_complete' => "تمت عملية نقل الصور والملفات المرفوعة.",
		'blobs_move_moved' => "تم نقل ^1 من ^2 الوثائق والصور المرفوعة",
		'blobs_stop' => "إيقاف النقل",
		'blobs_to_db' => "تقطير إلى قاعدة البيانات",
		'blobs_to_db_note' => "- نقل كل الصور والوثائق المرفوعة من ملفات القرص إلى قاعدة البيانات",
		'blobs_to_disk' => "تقطير إلى القرص",
		'blobs_to_disk_note' => "- نقل كل الصور والملفات المرفوعة من قاعدة البيانات إلى القرص",
		'block_button' => "منع",
		'cancel_mailing_button' => 'الغاء البريد',
		'categories_introduction' => 'لتبدأ التصنيفات، انقر على زر \'أضف تصنيف\'.',
		'categories_not_shown' => 'بعض الأسئلة التي تمتلك تصنيفات لن يتم عرضها.',
		'categories_title' => 'التصنيفات',
		'categories' => 'التصنيفات',
		'category_add_sub' => 'اضف تصنيف فرعي',
		'category_added' => 'تم إضافة التصنيف',
		'category_already_used' => 'هذه مستخدمة بالفعل في أحد التصنيفات',
		'category_default_slug' => 'تصنيف-^',
		'category_description' => 'وصف اختياري للتصنيف:',
		'category_max_depth_x' => 'بعض الخيارات قد تكون مخفية لمنع تعمق التصنيف أكثر من ^ من المستويات.',
		'category_move_parent' => 'الانتقال إلى رئيسي آخر',
		'category_name_first' => 'اسم أول تصنيف:',
		'category_name' => 'اسم التصنيف:',
		'category_no_add_subs_x' => 'لا يمكن انشاء تصنيفات فرعية لهذا التصنيف لأنه تحت ^ مستويات دنيا مسبقاً.',
		'category_no_delete_subs' => 'لايمكن حذف هذا التصنيف لأنه يحوي تصنيف فرعي.',
		'category_no_sub_error' => '^q سؤال\أسئلة في هذا التصنيف بدون تصنيف فرعي - ^1اصنع تصنيف فرعي^2',
		'category_no_sub_to' => 'نقل الأسئلة في ^ التي ليس لها تصنيف فرعي إلى:',
		'category_no_subs' => 'لا يوجد',
		'category_none_error' => '^q سؤال\أسئلة ليس لها تصنيف حالياً - ^1ضع تصنيف^2',
		'category_none_to' => 'انقل الأسئلة التي ليس لها تصنيف إلى:',
		'category_parent' => 'تصنيف رئيسي:',
#		'category_position' => 'موضع التصنيفات:',
		'category_saved' => 'تم حفظ التصنيف',
		'category_slug' => 'خليط التصنيف - نسق URL:',
		'category_subs' => 'تصنيفات فرعية:',
		'category_top_level' => 'لا يوجد رئيسي [المستوى الأعلى]',
		'characters' => 'رموز',
		'check_language_suffix' => ' - ^1تفحص ملفات اللغة^2',
#		'click_category_edit' => 'انقر على اسم التصنيف لتعدله:',
		'click_name_edit' => 'صفحات أو روابط مخصصة:',
		'database_cleanup' => 'عمليات تنظيف قاعدة البيانات',
		'delete_category_reassign' => 'احذف هذا التصنيف وأعد تعيين أسئلته إلى:',
		'delete_category' => 'احذف هذا التصنيف',
		'delete_field' => 'احذف هذا الحقل',
		'delete_hidden_complete' => 'تم حذف جميع الإدراجات المخفية التي لا تمتلك ارتباطات',
		'delete_hidden_note' => ' - جميع الأسئلة، والإجابات، والتعليقات المخفية بدون ارتباطات',
		'delete_hidden' => 'احذف الإدرجات المخفية',
		'delete_link' => 'احذف هذا الرابط',
		'delete_page' => 'احذف هذه الصفحة',
		'delete_stop' => 'إيقاف الحذف',
		'delete_title' => 'احذف هذه الرتبة',
		'delete_widget_position' => 'احذف هذه الأداة الإضافية من هذا الموضع',
		'edit_custom_page' => 'عدل الصفحة المخصصة',
		'edit_field' => ' - ^1عدل الحقل^2',
		'edit_link' => ' - ^1عدل الرابط^2',
		'edit_page' => ' - ^1عدل الصفحة^2',
		'edit_title' => ' - ^1عدل الرتبة^2',
		'emails_per_minute' => 'رسائل البريد لكل دقيقة',
		'emails_title' => 'البريد الإلكتروني',
		'feed_link_example' => 'مثال على التغذية',
		'feed_link' => 'التغذية',
		'feeds_title' => 'تغذية RSS',
		'field_link_url' => 'عنوان URL مرتبط',
		'field_multi_line' => 'سطور متعددة من النص',
		'field_name' => 'عنوان الحقل الذي سيتم عرضه:',
		'field_single_line' => 'سطر منفرد من النص',
		'field_type' => 'نوع الحقل:',
		'first' => 'الأول',
		'flagged_title' => 'معلًم',
		'from_anon' => 'من مجهول:',
#		'from_plugin' => ' [من إضافة: ^]',
		'from_users' => 'من المستخدمين:',
		'form_security_expired' => "انتهت مدة صلاحية شفرة أمان النموذج - يرجى المحاول ثانية",
		'ip_address_pages' => "صفحات عناوين مواثيق الانترنت IP",
		'approve_users_title' => "اعتماد المستخدمين",
		'module_x_database_init' => "تتطلب الوحدة ^1 ^2 بعضاً من ^3database قاعدة البينانات للتهئية^4.",
		'most_flagged_title' => "محتوى تم الإبلاغ عنه",
		'no_approve_found' => "لا يوجد محتوى بحاجة لإقرار",
		'no_flagged_found' => "لا يوجد محتوى إبلاغات إساءة",
		'no_unapproved_found' => "لا يوجد مستخدمين بانتظار الإقرار",
		'options' => "خيارات",
		'pause_mailing_button' => "إيقاف مؤقت للبريد",
		'per_ip_hour' => "لكل عنوان انترنت\ساعة IP/hour",
		'per_user_hour' => "لكل مستخجم في الساعة",
		'permit_to_view' => "مرئي لـ:",
		'pixels' => "بكسل",
		'plugin_module' => " (وحدة مضافة: ^)",
		'question_lists' => "قوائم الأسئلة",
		'question_pages' => "صفحات الأسئلة",
		'recalc_categories_backpaths' => "جاري إعادة حساب مسارات URL لـ  ^1 من ^2 وسوم...",
		'recalc_categories_recounting' => "جاري إعادة حساب أسئلة ^1 من ^2 وسوم...",
		'recent_approve_title' => "المحتوى الحالي في انتظار الاعتماد",
		'recount_posts_as_recounted' => "تم إعادة حساب ^1 إجابة وسخونة من ^2 مشاركة...",
		'recount_posts_votes_recounted' => "تم إعادة حساب ^1 تصويت وإبلاغ من ^2 مشاركة...",
		'requires_php_version' => "معطل - يتطلب إصدار PHP ^ أو أحدث",
		'resume_mailing_button' => "استئناف البريد",
		'send_test_button' => "راسلني بعينة فحص",
		'show_on_register_form' => "اظهار الحقل على نموذج التسجيل للمستخدم",
		'start_mailing_button' => "بدء البريد",
		'tag_pages' => "الصفحات",
		'test_sent_to_x' => "تم إرسال عينة الرسالة إلى ^",
		'top_level_categories' => "الوسوم عالية المستوى:",
		'user_pages' => "صفحات المستخدم",
		'users_must_have' => "يتطلب المستخدمون",
		'version_get_x' => "تحصيل ^",
		'version_requires_php' => "^1 يتطلب PHP ^2",
		'version_requires_q2a' => "^1 يتطلب Q2A ^2",
		'version_latest_unknown' => "المجهول الأحدث",
		'version_latest' => "الأحدث",
		'widget_all_pages' => "اظهر الأداة الإضافية في هذا الموضع على كل الصفحات المتاحة",
		'widget_global_options' => " - ^1خيارات^2",
		'widget_name' => "اسم الأداة الإضافية:",
		'widget_no_positions' => "سبق إضافة هذه الأداة إلى كل موضع متاح.",
		'widget_not_available' => "هذه الأداة الإضافية غير متوافرة. قد يكون السبب أن الأداة المسؤولة عنها قد ألغي تنصيبها.",
		'widget_pages_explanation' => "اظهر الأداة الإضافية في هذا الموضع على هذه الصفحات:",
		'widgets_explanation' => "الأدوات الإضافية:",

		'general_title' => 'عام',
		'hidden_answers_deleted' => 'احذف ^1 of ^2 الإجابات المخفية غير المرتبطة...',
		'hidden_comments_deleted' => 'احذف ^1 of ^2 التعليقات المخفية...',
		'hidden_questions_deleted' => 'احذف ^1 of ^2 الأسئلة المخفية غير المرتبطة...',
		'hidden_title' => 'المحتويات المخفية',
		'hotness_factors' => 'الأهمية النسبية لسخونة السؤال:',
#		'installed_plugins' => 'الإضافات المثبتة:',
		'layout_title' => 'التصميم',
		'link_name' => 'نص الرابط:',
		'link_new_window' => 'فتح الرابط في نافذة جديدة',
		'link_url' => 'عنوان URL للرابط (عنوان http:// كامل أو بالنسبة للمجلد الرئيسي للسكربت):',
		'lists_title' => 'قوائم',
		'mailing_complete' => 'هذا البريد مكتمل',
		'mailing_explanation' => 'يمكن للمستخدمين إلغاء الاشتراك عبر صفحة حسابهم.',
		'mailing_progress' => 'اكتمل البريد لـ ^1 من ^2 مستخدم...',
		'mailing_title' => 'البريد',
		'mailing_unsubscribe' => 'سيتم إضافة رابط إلغاء إشتراك إلى أسفل كل رسالة.',
		'maintenance_admin_only' => 'الموقع الآن تحت ^1الصيانة^2 وهو الآن غير متاح للمستخدمين.',
		'maximum_x' => ' [حد أعلى ^]',
		'moderate_title' => 'وساطة',
		'nav_links_explanation' => 'اظهر روابط الارتباطات التالية في كل صفحة :',
		'nav_qa_is_home' => 'س&ج [الروابط للصفحة الرئيسية]',
		'neat_urls_note' => ' [يتطلب ملف ^1htaccess^2]',
		'no_classification' => 'بدون تصنيف',
		'no_hidden_found' => 'لا توجد أسئلة، أو إجابات، أو تعليقات مخفية',
		'no_image_gd' => 'النسخة المثبتة من PHP تم إعدادها بدون دعم صورة GD ، لذلك لن يتمكن المستخدمون من رفع صورهم الشخصية مباشرة.',
		'no_link' => 'لا يوجد رابط',
		'no_multibyte' => 'النسخة المثبتة من PHP تم إعدادها بدون دعم تعدد البايتات. لذلك فإن عمليات البحث بالأحرف غير الرومانية لن تكون فعالة.',
#		'no_plugin_options' => 'لا توجد خيارات لعرضها لأي من الإضافات المثبتة.',
		'no_privileges' => 'فقط المدراء يمكنهم الولوج إلى هذه الصفحة.',
		'not_logged_in' => 'من فضلك ^1قم بتسجيل دخولك^2 كمدير لتتمكن من الولوج إلى هذه الصفحة.',
		'opposite_main_menu' => 'بعد ونهاية الجدولة في الأعلى',
		'options_reset' => 'تم إعادة تعيين الخيارات',
		'options_saved' => 'تم حفظ الخيارات',
		'page_already_used' => 'هذا مستخدم بالفعل بواسطة صفحة',
		'page_content_html' => 'محتويات لتعرض في الصفحة [أكواد HTML مسموح بها]:',
		'page_default_slug' => 'صفحة-^',
		'page_heading' => 'عنوان ليتم عرضه أعلى الصفحة:',
		'position' => 'الوضع:',
		'page_name' => 'اسم الصفحة (يستخدم أيضًا للشريط وللرابط):',
		'page_slug' => 'العنوان اللطيف للصفحة (هيئة عنوان UR;):',
		'pages_explanation' => 'أنقر على زر \'اضف صفحة\' لتضيف محتويات مخصصة إلى الموثع، أو \'اضف رابط\' للربط بأي صفحة ويب.',
		'pages_title' => 'الصفحات',
		'permissions_title' => 'الصلاحيات',
		'plugin_pages_explanation' => 'الصفحات الآتية متاحة عبر الإضافات:',
		'plugins_title' => 'الإضافات',
		'q2a_build_date' => 'تاريخ الإنشاء:',
		'q2a_db_size' => 'حجم قاعدة البيانات:',
		'basic_editor' => 'المحرر الأساسي',
		'q2a_version' => 'إصدار Question2Answer:',
		'q2a_db_version' => 'إصدار قاعدة البيانات لـ Question2Answer:',
		'q2a_latest_version' => 'آخر إصدار لـ Question2Answer:',
		'php_version' => 'إصدار PHP:',
		'mysql_version' => 'إصدار MySQL:',
		'points_defaults_shown' => 'الإعدادات الافتراضية معروضة بالأسفل لكن لم يتم تطبيقها:',
		'points_title' => 'النقاط',
		'points' => 'النقاط',
		'posting_title' => 'الإدراج',
		'recalc_categories_complete' => 'تم إعادة حساب جميع التصنيفات بنجاح.',
		'recalc_categories_note' => ' - لتصنيف الإدراجات وعدادات التصنيف',
#		'recalc_categories_recounting' => 'إعادة حساب مجاميع تصنيفات السؤال...',
		'recalc_categories_updated' => 'إعادة الحساب لـ ^1 من ^2 الإجابات والتعليقات...',
		'recalc_categories' => 'إعادة حساب التصنيفات',
		'recalc_points_complete' => 'تم إعادة حساب نقاط العضو بنجاح.',
		'recalc_points_note' => ' - لتصنيف العضو وعرض النقاط',
		'recalc_points_recalced' => 'إعادة الحساب لـ ^1 من ^2 مستخدمًا...',
		'recalc_points_usercount' => 'تقدير العدد الإجمالي للمستخدمين...',
		'recalc_points' => 'إعادة حساب نقاط العضة',
		'recalc_posts_count' => 'الحصول على العدد الإجمالي للأسئلة، والإجابات والتعليقات...',
		'recalc_stop' => 'إيقاف إعادة الحساب',
#		'recaptcha_fsockopen' => 'لاستخدام الصورة التأكيدية (reCAPTCHA)، دالة fsockopen() في PHP يجب تفعيلها على خادمك. من فضلك تواصل مع مدير الخادم الخاص بك.',
#		'recaptcha_get_keys' => 'لتستخدم الصورة التأكيدية (reCAPTCHA)، يجب عليك ^1تسجيل حساب^2 للحصول على هذه المفاتيح.',
		'recent_hidden_title' => 'آخر الأسئلة بمحتويات مخفية',
		'recount_posts_complete' => 'تم إعادة عد جميع الأسئلة والإجابات بنجاح',
		'recount_posts_note' => ' - عدد الإجابات والتصويتات لكل إدراج',
#		'recount_posts_recounted' => 'إعاد عد لـ ^1 من ^2 سؤال وإجابة...',
		'recount_posts_stop' => 'إيقاف العد',
		'recount_posts' => 'آخر الأسئلة والإجابات',
		'refill_events_complete' => 'تمت إعادة تعبئة جداول الأحداث جميعها بنجاح',
		'refill_events_note' => ' - لكل قائمة مستخدم من التحديثات',
		'refill_events_refilled' => 'تمت إعادة التعبئة لـ ^1 من ^2 سؤال...',
		'refill_events' => 'أعد تعبئة جداول الأحداث',
		'registration_fields' => "إضافة حقول تسجيل",
		'reindex_content' => 'أعد فهرسة المحتوى',
		'reindex_content_note' => ' - للبحث واقتراحات متعلقة بالسؤال',
		'reindex_content_stop' => 'إيقاف إعادة الفهرسة',
		'reindex_pages_reindexed' => 'تمت إعادة فهرسة ^1 من ^2 صفحة...',
		'reindex_posts_complete' => 'تم إعادة فهرسة جميع الأسئلة، والإجابات، والتعليقات بنجاح.',
#		'reindex_posts_note' => ' - للبحث واقتراحات الأسئلة المتعلقة',
		'reindex_posts_reindexed' => 'إعادة فهرسة ^1 من ^2 أسئلة، وإجابات، وتعليقات...',
#		'reindex_posts_stop' => 'إيقاف إعادةالفهرسة',
		'reindex_posts_wordcounted' => 'إعادة عد ^1 من ^2 كلمة...',
#		'reindex_posts' => 'إعادة فهرسة الأسئلة، والإجابات، والتعلقات',
		'reset_options_button' => 'إعادة الإفتراضات',
		'reset_options_confirm' => 'هل أنت متأكد من إعادة تعيين جميع الخيارات في هذه الصفحة لوضعها الافتراضي؟',
		'save_options_button' => 'حفظ الخيارات',
		'save_recalc_button' => 'احفظ وأعد الحساب',
		'save_view_button' => 'حفظ وعرض',
		'show_defaults_button' => 'اعرض الافتراضات',
		'slug_bad_chars' => 'الرابط اللطيف لا ينبغي أن يحتوي على هذه الحروف: ^',
		'slug_reserved' => 'هذا الرابط اللطيف تم استقباله ليمكن استخدامه في صفحة أخرى',
		'spam_title' => 'السبام',
		'stats_title' => 'الإحصاءات',
		'stop_recalc_warning' => 'عملية تنظيف قاعدة البيانات جارية. إذا قمت بإغلاق هذه الصفحة الآن، سيتم إيقاف العملية.',
		'tags_and_categories' => 'الوسوم والتصنيفات',
		'tags_not_shown' => 'بعض الأسئلة التي تمتلك وسومًا لن يتم عرضها.',
		'tags' => 'الوسوم',
		'title_already_used' => 'هذه القيمة مستخدمة بالفعل في رتبة أخرى',
		'total_as' => 'إجمالي الإجابات:',
		'total_cs' => 'إجمالي التعليقات:',
		'total_qs' => 'إجمالي الأسئلة:',
		'unnamed_plugin' => 'إضافة غير مسماة',
		'requires_q2a_version' => 'تم الإيقاف - يحتاج نسخة Question2Answer ^ أو أعلى',
		'upgrade_db' => 'قاعدة بيانات Question2Answer تحتاج إلى ^1الترقية^2 لهذه الإصدارة.',
		'url_format_note' => 'الخيارات التي تحمل علامة ^ ستعمل بنجاح مع إعدادات موقعك. لأفضل توافق مع معايير محركات البحث، استخدم أول خيار متاح معلم بـ ^ .',
		'users_active' => 'المستخدمون النشطون:',
		'user_titles' => 'رتب المستخدمين بحسب النقاط:',
		'profile_fields' => 'الحقول الإضافية في الملف الشخصي للمستخدم:',
		'users_posted' => 'المستخدمون الذين أرسلوا إدراجات:',
		'users_registered' => 'المستخدمون المسجلون:',
		'users_title' => 'المستخدمون',
		'user_title' => 'رتبة المستخدم (مسموح بأكواد HTML):',
		'points_required' => 'النقاط المطلوبة للحصول على الرتبة:',
		'users_voted' => 'المستخدمون الذين صوتوا:',
		'viewing_title' => 'العرض',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
