<?php
	
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => 'إجابة واحدة',
		'a_convert_to_c_on' => 'حول هذه الإجابة إلى تعليق على:',
		'a_convert_to_c' => 'حول هذه الإجابة إلى تعليق',
		'a_convert_warn_cs' => 'تحذير: هذه المحادثة لا يمكن استقبالها، وسيتم أيضًا تحويل التعليقات على الإجابة [أو الإجابات].',
		'a_convert_warn' => 'تحذير: هذه المحادثة لا يمكن استقبالها.',
		'a_notify_email' => 'أعلمني على هذا العنوان الإلكتروني إذا تم اختيار إجابتي أو تم التعليق عليها:',
		'a_notify_label' => 'أعلمني إذا ما تم اختيار إجابتي أو تم التعليق عليها',
		'a_notify_x_label' => 'أعلمني بالبريد الإلكتروني [^] إذا تم اختيار إجابتي أو تم التعليق عليها',
		'a_waiting_your_approval' => 'هذه الإجابة تنتظر موافقتك',
		'a_your_waiting_approval' => 'سيتم مراجعة إجابتك والموافقة عليها قريباً.',
		'add_answer_button' => 'إضافة الإجابة',
		'add_comment_button' => 'إضافة تعليق',
		'add_q_favorites' => 'اضف هذا السؤال إلى المفضلة',
		'anon_name_label' => 'اسمك الذي سيظهر (اختياري):',
		'answer_button' => 'إجابة',
		'answer_limit' => 'تم استقبال الكثير من الإجابات، من فضلك حاول مرة أخرى لاحقًا',
		'answer_must_be_approved' => 'يجب الموافقة على حسابك قبل إمكانية الرد على سؤل هنا.',
		'answer_must_confirm' => 'من فضلك ^5أكد عنوان بريدك الإلكتروني^6 للإجابة على هذا السؤال.',
		'answer_must_login' => 'من فضلك ^1سجل دخولك^2 أو ^3قم بتسجيل حساب^4 للإجابة على هذا السؤال',
		'answer_q_popup' => 'أجب عن هذا السؤال',
		'approve_a_popup' => 'الموافقة على هذه الإجابة',
		'approve_button' => 'اعتماد',
		'approve_c_popup' => 'الموافقة على هذا التعليق',
		'approve_q_popup' => 'الموافقة على هذا السؤال',
		'ask_button' => 'اطرح سؤالك',
		'ask_follow_from_a' => 'سؤالك سيكون ذا علاقة بهذه الإجابة:',
		'ask_follow_title' => 'اطرح  سؤالاً ذا علاقة',
		'ask_limit' => 'تم استقبال الكثير من الأسئلة، من فضلك حاول مرة أخرى لاحقًا',
		'ask_must_be_approved' => 'يجب اعتماد حسابك قبل أن تتمكن من طرح سؤال هنا.',
		'ask_must_confirm' => 'من فضلك ^5أكد عنوان بريدك الإلكتروني^6 لتتمكن من طرح سؤال',
		'ask_must_login' => 'من فضلك ^1قم بتسجيل دخولك^2 أو ^3قم بتسجيل حساب^4 لتتمكن من السؤال',
		'ask_same_q' => 'قبل المتابعة، من فضلك تأكد أن سؤالك لم يتم طرحه من قبل:',
		'ask_title' => 'اطرح سؤالاً',
		'c_notify_email' => 'أعلمني على هذا البريد الإلكتروني إذا تم إضافة تعليق بعدي:',
		'c_notify_label' => 'أعلمني على بريدي الإلكتروني إذا تم إضافة تعليق بعدي',
		'c_notify_x_label' => 'أعلمني على بريدي الإلكتروني [^] إذا تم إضافة تعليق بعدي',
		'c_waiting_your_approval' => 'هذا التعليق ينتظر اعتمادك',
		'c_your_waiting_approval' => 'تعليقك سيتم مراجعته واعتماده قريباً.',
		'category_js_note' => 'لاختيار أي تصنيف، يرجى تمكين جافا سكربت في متصفحك.',
		'category_ask_not_allowed' => 'لا تملك صلاحيات طرح سؤال في هذا التصنيف',
		'category_required' => 'الرجاء اختيار تصنيف',
		'claim_button' => 'أنا قمت بكتابة هذا',
		'claim_a_popup' => 'تعيين هذه الإجابة إلى حساب المستخدم الخاص بك',
		'claim_c_popup' => 'تعيين هذا التعليق لحساب المستخدم الخاص بك',
		'claim_q_popup' => 'تعيين هذا السؤال لحساب المستخدم الخاص بك',
		'clear_flags_button' => 'محو المشاركات المعلمة بالإساءة',
		'clear_flags_popup' => 'إزالة أعلام الإساءة من جميع المستخدمين',
		'close_button' => 'غلق',
		'close_duplicate_error' => 'تعذر الحصول على التكرار-  حاول إدخال الرقم في رابط  URL آخر مثل 123.',
		'close_duplicate' => '◄─────  هذا سؤال مكرر لسؤال آخر',
		'close_form_button' => 'غلق',
		'close_form_title' => 'أغلق هذا السؤال عن أي إجابة جديدة',
		'close_original_note' => 'بإمكانك أيضاً إدراج رقم السؤال من عنوان URL، مثل 123.',
		'close_original_title' => 'رابط URL السؤال الأصلي:',
		'close_q_popup' => 'اقفل هذا السؤال عن أي إجابات جديدة',
		'close_reason_title' => 'سبب إغلاق هذا السؤال:',
		'closed_as_duplicate' => 'هذا تكرار لسؤال آخر:',
		'closed_with_note' => 'تم إغلاقه بملاحظة:',
		'comment_a_popup' => 'اكتب تعليقًا على هذه الإجابة',
		'comment_button' => 'علق',
		'comment_limit' => 'تم استقبال الكثير من التعليقات، من فضلك حاول مرة أخرى لاحقًا',
		'comment_must_be_approved' => 'ينبغي الموافقة على حسابك قبل أن تتمكن من إضافة تعليق هنا.',
		'comment_must_confirm' => 'من فضلك ^5أكد عنوان بريدك الإلكتروني^6 لتتمكن من إضافة تعليق',
		'comment_must_login' => 'من فضلك ^1قم بتسجيل دخولك^2 أو ^3قم بتسجيل حساب^4 لتتمكن من إضافة تعليق',
		'comment_on_a' => 'في الإجابة: ',
		'comment_on_q' => 'في السؤال: ',
		'comment_q_popup' => 'أضف تعليقًا على هذا السؤال',
#		'continue_button' => 'تابع',
		'delete_a_popup' => 'احذف هذه الإجابة بشكل دائم',
		'delete_button' => 'احذف',
		'delete_c_popup' => 'احذف هذا التعليق بشكل دائم',
		'delete_q_popup' => 'احذف هذا السؤال بشكل دائم',
#		'different_button' => 'سؤالي مختلف عن هذا',
		'duplicate_content' => 'إدخالك يبدو مكررًا.',
		'edit_a_popup' => 'عدل هذه الإجابة',
		'edit_a_title' => 'عدل إجابة',
		'edit_button' => 'عدل',
		'edit_c_popup' => 'عدل هذا التعليق',
		'edit_c_title' => 'عدل تعليق',
		'edit_must_confirm' => 'من فضلك ^5أكد عنوان بريدك الإلكتروني^6 لتتمكن من تعديل هذا.',
		'edit_must_login' => 'من فضلك ^1سجل دخولك^2 أو ^3قم بتسجيل حساب^4 لتتمكن من تعديل هذا',
		'edit_q_popup' => 'عدل هذا السؤال',
		'edit_q_title' => 'عدل سؤال',
#		'edited_x_ago' => 'عدل منذ ^',
#		'edited' => 'تم تعيله',
		'example_tags' => 'أمثلة الوسوم ',
		'flag_a_popup' => 'علم هذه الإجابة على أنها غير مناسبة',
		'flag_button' => 'إبلاغ إساءة',
		'flag_c_popup' => 'علم هذاالتعليق على أنه غير مناسب',
		'flag_hide_button' => 'إبلاغ إساءة  وإخفاء',
		'flag_limit' => 'مشاركات عديدة تم تعليمها كإساءة - يرجى المحاولة بعد ساعة',
		'flag_must_confirm' => 'فضلاً ^5أكّد بريدك الإلكتروني ^6 لتعليم المشاركات.',
		'flag_must_login' => 'فضلاً ^1سجل الدخول^2 أو^3اشترك^4 لتعليم المشاركات.',
		'flag_not_allowed' => 'تعليم هذا غير مسموح',
		'flag_q_popup' => 'علّم هذا السؤال على أنه غير مناسب',
		'follow_a_popup' => 'اطرح  سؤالاً جديدًا ذا صلة  بهذه الإجابة',
		'follow_button' => 'اطرح  سؤالاً ذا صلة',
		'follows_a' => 'ذو علاقة بإجابة على:',
		'follows_q' => 'عن هذا السؤال:',
#		'hidden_x_ago' => 'مخفي منذ ^',
#		'hidden' => 'مخفي',
		'hide_a_popup' => 'اخف هذه الإجابة',
		'hide_button' => 'اخف',
		'hide_c_popup' => 'اخف هذا التعليق',
		'hide_q_popup' => 'اخف هذا السؤال',
		'matching_tags' => 'وسوم مطابقة ',
		'min_tags_x' => 'من فضلك أدخل ^ وسماً على الأقل',
		'max_tags_x' => 'العدد الأقصى المسموح به للوسوم هو ^',
		'notify_email_note' => 'نحن نحرص على خصوصيتك: هذا العنوان البريدي لن يتم استخدامه لغير إرسال التنبيهات.',
		'q_category_label' => 'التصنيف:',
		'q_content_label' => 'معلومات أكثر عن سؤالك:',
		'q_hidden_author' => 'هذا السؤال تم إخفاءه بواسطة كاتبه',
		'q_hidden_flagged' => 'هذا السؤال تم تعليمه وإخفاءه',
		'q_hidden_other' => 'هذا السؤال تم إخفاءه',
#		'q_not_found' => 'لم ينم إيجاد السؤال',
		'q_notify_email' => 'أعلمني على هذا العنوان البريدي الإلكتروني إذا ما تم إجابة سؤالي أو تم التعليق عليه:',
		'q_notify_label' => 'أعلمني على بريدي الإلكتروني إذا ما تم إجابة سؤالي أو تم التعليق عليه',
		'q_notify_x_label' => 'أعلمني على بريدي الإلكتروني [^] إذا ما تم إجابة سؤالي أو تم التعليق عليه',
		'q_tags_comma_label' => 'الوسوم - استعمل الفاصلة (,) للفصل:',
		'q_tags_label' => 'أدخل وسوماً للسؤال (الوسوم هي كلمات مفتاحية تصف بها محتوى الموضوع)، افصل بين كل وسم وآخر بمسافة:',
		'q_title_label' => 'اطرح سؤالك في جملة واحدة:',
#		'q_title_note' => 'يمكنك تقديم المزيد من المعلومات لاحقًا.',
		'q_waiting_approval' => 'هذا السؤال ينتظر موافقة',
		'q_waiting_your_approval' => 'هذا السؤال ينتظر موافقتك',
		'q_your_waiting_approval' => 'سؤالك سيتم مراجعته واعتماده قريباً.',
		'recat_button' => 'إعادة تصنيف',
		'recat_popup' => 'غير تصنيف هذا السؤال',
		'recat_q_title' => 'أعد تصنيف السؤال',
		'reject_a_popup' => 'رفض هذه الإجابة',
		'reject_button' => 'رفض',
		'reject_c_popup' => 'رفض هذا التعليق',
		'reject_q_popup' => 'رفض هذا السؤال',
		'remove_q_favorites' => 'إزالة هذا السؤال من المفضلة',
		'reopen_button' => 'إعادة فتح',
		'reopen_q_popup' => 'إعادة فتح هذا السؤال',
		'reply_button' => 'رد',
		'reply_c_popup' => 'رد على هذا التعليق',
		'reshow_a_popup' => 'إعادة عرض هذه الإجابة',
		'reshow_button' => 'أظهر مرة أخرى',
		'reshow_c_popup' => 'إعادة عرض هذا التعليق',
		'reshow_q_popup' => 'إعادة عرض هذا السؤال',
		'retag_button' => 'إعادة وسم',
		'retag_cat_popup' => 'تغيير صنف أو وسم هذا السؤال',
		'retag_popup' => 'تغيير وسم هذا السؤال',
		'retag_q_title' => 'أعد وسم السؤال',
		'save_silent_label' => 'حفظ صامت لإخفاء أنه تم التعديل', 
		'select_popup' => 'أنقر لتختار هذه الإجابة كأفضل إجابة',
		'select_text' => 'أفضل إجابة',
		'show_1_comment' => 'غظهر تعليق واحد',
		'show_1_previous_comment' => 'اظهر تعليق سابق',
		'show_x_comments' => 'اظهر ^ تعليق',
		'show_x_previous_comments' => 'اظهر ^ تعليق سابق',
		'unflag_button' => 'إزالة العلم',
		'unflag_popup' => 'إزالة التعليم الذي أضفته',
		'unselect_popup' => 'أنقر لتحذف اختيارك',
		'x_answers_title' => '^ إجابة',
		'your_answer_title' => 'إجابتك',
		'your_comment_a' => 'تعليقك على هذه الإجابة:',
		'your_comment_q' => 'تعليقك على هذا السؤال:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
